name: Testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compiling 
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxwren .
          cd sample
          haxe build.hxml
